gam.pyxplot.png: gam.data.txt gam.tab.txt Makefile
	echo '\
	set terminal png ;\
	set output "$@" ;\
	set xlabel "$$x$$" ;\
	set ylabel "$$y$$" ;\
	set tics out ;\
	set title "Gamma function (app.)" ;\
	set key left top ;\
	plot [-5:5] [-5:5] "$<" index 0 using 1:2 with lines title "Gamma function",\
	"gam.tab.txt" using 1:2 with points pointtype 2 title "Tabulated data" \
	'| tee log.pyx.gpi | pyxplot

gam.tab.txt: Makefile
	>$@
	echo 1	1	0 >>$@
	echo 2	1	0 >>$@
	echo 3	2	0.69314718055994530941723212145818 >>$@
	echo 4  6	1.7917594692280550008124773583807 >>$@


gam.data.txt: main.exe
	mono $< > $@

all: Out.txt
	cat $<

Out.txt: main.exe
	 mono main.exe > Out.txt

main.exe: main.cs
	mcs -target:exe -out:$@ $<

clean:
	rm -f main.exe Out.txt
